apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/name: oauth2-proxy
  name: oauth2-proxy
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
